# Generated by Django 4.2.2 on 2023-06-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DONER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('organ', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
